# baseURL = 'https://example.org/'
# languageCode = 'en-us'
# title = 'My New Hugo Site'
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Adrian's Blog"
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "Adrian's Personal Blog"

# Appearance settings
#theme = 'auto'
theme = 'dark'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = "About Me"
homeIntroContent = """
Hey there, a Grad Student at Purdue University currently working on Supply Chain Security and Privacy Technologies.
"""

# Collection to display on home
# homeCollectionTitle = 'Posts'
# homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/adrian-persaud-65b0a31bb"

[[params.social]]
name = "github"
url = "https://github.com/adrianpersaud"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

# [[params.menu]]
# name = "posts"
# url = "/posts"
# 
# [[params.menu]]
# name = "about"
# url = "/about"

[[params.menu]]
name = "gpg-key"
url = "/gpg-key"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
